-- Add analytics cache table for the Admin BI dashboard.
-- One row per time range; regenerated by cron and the manual "Refresh" button.
CREATE TABLE IF NOT EXISTS analytics_cache (
  range TEXT PRIMARY KEY,          -- '7d' | '30d' | '90d'
  payload TEXT NOT NULL,           -- JSON: insights, alerts, recommendations, metrics, trends
  generated_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);
