/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/observability-tail/wrangler.jsonc --include-runtime=false --env-interface=ObservabilityTailEnv workers/observability-tail/worker-configuration.d.ts` (hash: 5f2ca70e617c6001f53d9195b7a51b08)
interface __BaseEnv_ObservabilityTailEnv {
	ALERT_EMAIL: SendEmail;
	EMAIL_PROVIDER: "cloudflare";
	ALERT_EMAIL_TO: "configure@example.invalid";
	ALERT_EMAIL_FROM: "configure@example.invalid";
	ALERT_SUBJECT_PREFIX: "configure-me";
	OPERATOR_IDENTITY: "configure-me";
	ENVIRONMENT: "configure-me";
	ALERT_COOLDOWN_SECONDS: "900";
	ALERT_FAILURE_BACKOFF_SECONDS: "30";
	ALERT_COOLDOWN: DurableObjectNamespace<import("./src/index").AlertCooldown>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "AlertCooldown";
	}
	interface Env extends __BaseEnv_ObservabilityTailEnv {}
}
interface ObservabilityTailEnv extends __BaseEnv_ObservabilityTailEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_PROVIDER" | "ALERT_EMAIL_TO" | "ALERT_EMAIL_FROM" | "ALERT_SUBJECT_PREFIX" | "OPERATOR_IDENTITY" | "ENVIRONMENT" | "ALERT_COOLDOWN_SECONDS" | "ALERT_FAILURE_BACKOFF_SECONDS">> {}
}
