INSERT INTO categories (name, slug, description, hero_image_url) VALUES
  ('Featured', 'featured', 'Our top picks', 'https://placeimg.com/347/594/any'),
  ('Sale', 'sale', 'Discounted items', 'https://placekitten.com/569/625'),
  ('Camping', 'camping', 'Gear for the outdoors', 'https://placeimg.com/225/930/any'),
  ('Apparel', 'apparel', 'Wearable gear', 'https://www.lorempixel.com/11/447'),
  ('Tools', 'tools', 'Field-ready tools', 'https://www.lorempixel.com/152/915'),
  ('Tech', 'tech', 'Outdoor electronics', 'https://www.lorempixel.com/224/283'),
  ('Hydration', 'hydration', 'Water gear', 'https://www.lorempixel.com/247/273'),
  ('Navigation', 'navigation', 'Find your way', 'https://placeimg.com/341/141/any');

INSERT INTO products (name, slug, description, primary_image_url, active, availability, on_sale) VALUES
  ('Road East Tool', 'road-east-tool-0', 'Understand investment note look own. Nothing build election available. This information some or.', 'https://dummyimage.com/594x978', True, 'available', True),
  ('Section Sell Device', 'section-sell-device-1', 'Nothing reason identify issue stay everybody. Nice main sit let bag improve. Participant hundred month focus.', 'https://placeimg.com/617/632/any', True, 'available', False),
  ('Result Participant Tool', 'result-participant-tool-2', 'City recent player rate marriage impact food movement. Early but central center day edge rock increase.', 'https://placeimg.com/447/739/any', True, 'coming_soon', True),
  ('Discuss Doctor Kit', 'discuss-doctor-kit-3', 'Education measure behind responsibility certainly sister opportunity hot. Even official onto record measure change. Suddenly way admit keep low.', 'https://dummyimage.com/290x758', True, 'available', True),
  ('Bring Others Pack', 'bring-others-pack-4', 'Participant only force recent those manage. Hope bag carry their single drive. Process cover notice very west whatever no. Degree take class catch.', 'https://dummyimage.com/898x867', True, 'coming_soon', False),
  ('Authority Another Device', 'authority-another-device-5', 'Animal street present pressure why. Perhaps gun let he dream east. Life person stand picture should. School trouble result crime deal.', 'https://placekitten.com/56/89', True, 'available', False),
  ('Generation Whether Pack', 'generation-whether-pack-6', 'Party wait strong improve job single player. Ten weight write show bad. Data guess save build.', 'https://placekitten.com/147/510', True, 'available', False),
  ('They Trouble Device', 'they-trouble-device-7', 'Forget believe beautiful you state me wife. Add they baby never. Director own suffer.', 'https://placeimg.com/902/442/any', True, 'coming_soon', True),
  ('Fish Allow Device', 'fish-allow-device-8', 'Believe Republican part tree throughout.', 'https://dummyimage.com/442x716', True, 'coming_soon', False),
  ('Goal Whatever Tool', 'goal-whatever-tool-9', 'Score authority become film control.', 'https://placekitten.com/685/720', True, 'available', True),
  ('Receive Leader Kit', 'receive-leader-kit-10', 'Knowledge bank serious apply attack. Article both teach environment several series enjoy drug.', 'https://dummyimage.com/1023x846', True, 'coming_soon', True),
  ('Almost Consider Kit', 'almost-consider-kit-11', 'Reality try international talk more area always raise. Now buy discover mind beyond executive nothing. With concern possible student. After rather them attack try.', 'https://placekitten.com/838/592', True, 'coming_soon', True),
  ('Whose Success Pack', 'whose-success-pack-12', 'Hear off red situation phone effect seat. Hour high take leave local experience certainly pay.', 'https://placeimg.com/255/219/any', True, 'coming_soon', False),
  ('Result Piece Device', 'result-piece-device-13', 'Mention most sea order doctor. Form candidate husband official report. Cup wait half sell hand view.', 'https://placekitten.com/926/854', True, 'available', False),
  ('Save Word Tool', 'save-word-tool-14', 'Between your marriage policy window main dark. Movement suddenly technology available top few. Maybe music task next artist perhaps.', 'https://dummyimage.com/989x843', True, 'coming_soon', True),
  ('Film Total Kit', 'film-total-kit-15', 'Decade successful exactly guy would note. Million free play. Most capital out own team manage.', 'https://placekitten.com/738/475', True, 'available', True),
  ('Analysis Beautiful Device', 'analysis-beautiful-device-16', 'Loss Mr whether. People your factor dream necessary.', 'https://dummyimage.com/286x249', True, 'coming_soon', False),
  ('Which Remain Device', 'which-remain-device-17', 'Public your ok born manage something. Feel give compare assume just work.', 'https://placekitten.com/105/182', True, 'coming_soon', True),
  ('May Hit Device', 'may-hit-device-18', 'Her safe blue and heavy effort. Movement style report enjoy front return.', 'https://placeimg.com/186/10/any', True, 'available', True),
  ('Meeting Thing Kit', 'meeting-thing-kit-19', 'At near act technology range. For reveal anything worry agency child read. Power eat shake one investment offer. Star others social local including can while.', 'https://www.lorempixel.com/945/312', True, 'coming_soon', False),
  ('Finish True Kit', 'finish-true-kit-20', 'Cover have yet store. Purpose maintain option worry lot down rule. Figure usually several none around adult plant.', 'https://placeimg.com/587/6/any', True, 'available', True),
  ('Write Performance Device', 'write-performance-device-21', 'Me government sit. Mind their if than memory. Process serve mother arm effort watch plant.', 'https://placeimg.com/390/263/any', True, 'coming_soon', True),
  ('Rate Evidence Device', 'rate-evidence-device-22', 'Outside mean challenge here nor sound field again. Relationship short about meet true cover opportunity.', 'https://placeimg.com/27/752/any', True, 'coming_soon', True),
  ('Not Old Kit', 'not-old-kit-23', 'Draw happy leader why. Production store out law present inside. Reflect get professional father one color.', 'https://placeimg.com/96/116/any', True, 'available', False),
  ('Phone Above Kit', 'phone-above-kit-24', 'Work bank unit.', 'https://placekitten.com/82/788', True, 'available', True),
  ('Rock Keep Tool', 'rock-keep-tool-25', 'Single nor grow remember popular board mother. Soon several last education more consumer.', 'https://placekitten.com/527/923', True, 'available', True),
  ('Else Project Tool', 'else-project-tool-26', 'Provide heart difference consumer car forget your nature. Campaign should city beyond expect look perform. Player sport physical trial.', 'https://placeimg.com/352/893/any', True, 'coming_soon', False),
  ('Law Across Device', 'law-across-device-27', 'Spend keep story cut relate customer camera. Simple floor adult answer born from drive. Mission treat amount father. Window nothing school whether product news section.', 'https://placeimg.com/842/91/any', True, 'coming_soon', False),
  ('Can Keep Tool', 'can-keep-tool-28', 'Inside anyone question statement same important.', 'https://placekitten.com/669/736', True, 'coming_soon', True),
  ('Generation Other Device', 'generation-other-device-29', 'Wrong commercial share agreement remember high range. Of take even who end animal.', 'https://www.lorempixel.com/481/999', True, 'available', False);

INSERT INTO product_categories (product_id, category_id) VALUES
  (1, 2),
  (1, 6),
  (1, 7),
  (1, 8),
  (2, 4),
  (2, 7),
  (3, 1),
  (3, 2),
  (3, 5),
  (3, 6),
  (3, 8),
  (4, 2),
  (4, 5),
  (4, 6),
  (4, 7),
  (5, 5),
  (5, 6),
  (6, 5),
  (6, 6),
  (6, 8),
  (7, 1),
  (7, 4),
  (7, 6),
  (7, 8),
  (8, 2),
  (8, 7),
  (9, 5),
  (9, 6),
  (10, 2),
  (10, 4),
  (11, 2),
  (11, 5),
  (11, 6),
  (11, 8),
  (12, 2),
  (12, 4),
  (12, 7),
  (12, 8),
  (13, 1),
  (13, 5),
  (13, 7),
  (13, 8),
  (14, 4),
  (14, 5),
  (14, 6),
  (15, 2),
  (15, 5),
  (15, 6),
  (16, 2),
  (16, 4),
  (16, 6),
  (16, 7),
  (17, 4),
  (17, 6),
  (17, 8),
  (18, 2),
  (18, 4),
  (18, 5),
  (19, 2),
  (19, 4),
  (19, 5),
  (19, 8),
  (20, 5),
  (20, 6),
  (20, 7),
  (21, 2),
  (21, 4),
  (21, 5),
  (21, 8),
  (22, 2),
  (22, 6),
  (22, 8),
  (23, 1),
  (23, 2),
  (23, 6),
  (23, 7),
  (24, 4),
  (24, 6),
  (24, 8),
  (25, 2),
  (25, 4),
  (25, 5),
  (25, 7),
  (26, 1),
  (26, 2),
  (26, 4),
  (26, 6),
  (26, 7),
  (27, 4),
  (27, 6),
  (28, 4),
  (28, 5),
  (29, 1),
  (29, 2),
  (29, 7),
  (30, 8);

INSERT INTO product_prices (product_id, price, currency) VALUES
  (1, 12226, 'USD'),
  (2, 29970, 'USD'),
  (3, 13491, 'USD'),
  (4, 22636, 'USD'),
  (5, 22216, 'USD'),
  (6, 8116, 'USD'),
  (7, 24605, 'USD'),
  (8, 14632, 'USD'),
  (9, 16706, 'USD'),
  (10, 24574, 'USD'),
  (11, 8290, 'USD'),
  (12, 10684, 'USD'),
  (13, 25551, 'USD'),
  (14, 21687, 'USD'),
  (15, 23394, 'USD'),
  (16, 17669, 'USD'),
  (17, 6729, 'USD'),
  (18, 28143, 'USD'),
  (19, 5426, 'USD'),
  (20, 22526, 'USD'),
  (21, 15020, 'USD'),
  (22, 15284, 'USD'),
  (23, 20228, 'USD'),
  (24, 5805, 'USD'),
  (25, 26437, 'USD'),
  (26, 19396, 'USD'),
  (27, 28694, 'USD'),
  (28, 25561, 'USD'),
  (29, 11798, 'USD'),
  (30, 11497, 'USD');

INSERT INTO product_sale_prices (product_id, sale_price, currency) VALUES
  (1, 9169, 'USD'),
  (3, 10118, 'USD'),
  (4, 16977, 'USD'),
  (8, 10974, 'USD'),
  (10, 18430, 'USD'),
  (11, 6217, 'USD'),
  (12, 8013, 'USD'),
  (15, 17545, 'USD'),
  (16, 13251, 'USD'),
  (18, 21107, 'USD'),
  (19, 4069, 'USD'),
  (21, 11265, 'USD'),
  (22, 11463, 'USD'),
  (23, 15171, 'USD'),
  (25, 19827, 'USD'),
  (26, 14547, 'USD'),
  (29, 8848, 'USD');

INSERT INTO product_inventory (product_id, quantity_in_stock) VALUES
  (1, 42),
  (2, 47),
  (3, 20),
  (4, 2),
  (5, 23),
  (6, 32),
  (7, 8),
  (8, 34),
  (9, 31),
  (10, 31),
  (11, 7),
  (12, 13),
  (13, 40),
  (14, 50),
  (15, 5),
  (16, 49),
  (17, 45),
  (18, 50),
  (19, 13),
  (20, 30),
  (21, 28),
  (22, 6),
  (23, 32),
  (24, 19),
  (25, 38),
  (26, 16),
  (27, 47),
  (28, 27),
  (29, 4),
  (30, 23);