INSERT INTO categories (name, slug, description, hero_image_url) VALUES
  ('Featured', 'featured', 'Our top picks', 'https://placeimg.com/347/594/any'),
  ('Sale', 'sale', 'Discounted items', 'https://placekitten.com/569/625'),
  ('Camping', 'camping', 'Gear for the outdoors', 'https://placeimg.com/225/930/any'),
  ('Apparel', 'apparel', 'Wearable gear', 'https://www.lorempixel.com/11/447'),
  ('Tools', 'tools', 'Field-ready tools', 'https://www.lorempixel.com/152/915'),
  ('Tech', 'tech', 'Outdoor electronics', 'https://www.lorempixel.com/224/283'),
  ('Hydration', 'hydration', 'Water gear', 'https://www.lorempixel.com/247/273'),
  ('Navigation', 'navigation', 'Find your way', 'https://placeimg.com/341/141/any');

INSERT INTO products (name, slug, description, primary_image_url, active, availability, on_sale) VALUES
('Rapid Wave Kit', 'rapid-wave-kit-6', 'Rapid Wave Kit is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/rapid-wave-kit-6.png', 1, 'available', 0),
('Vivid Mission Pack', 'vivid-mission-pack-0', 'Vivid Mission Pack is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/vivid-mission-pack-0.png', 1, 'coming_soon', 1),
('Dusty Fire Tool', 'dusty-fire-tool-1', 'Dusty Fire Tool is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/dusty-fire-tool-1.png', 1, 'available', 0),
('Echo Sky Kit', 'echo-sky-kit-2', 'Echo Sky Kit is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/echo-sky-kit-2.png', 1, 'available', 0),
('Lunar Signal Pack', 'lunar-signal-pack-3', 'Lunar Signal Pack is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/lunar-signal-pack-3.png', 1, 'available', 0),
('Twin Dune Tool', 'twin-dune-tool-4', 'Twin Dune Tool is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/twin-dune-tool-4.png', 1, 'available', 0),
('Polar Leaf Device', 'polar-leaf-device-5', 'Polar Leaf Device is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/polar-leaf-device-5.png', 1, 'available', 0),
('Eagle Shadow Tool', 'eagle-shadow-tool-7', 'Eagle Shadow Tool is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/eagle-shadow-tool-7.png', 1, 'available', 0),
('Rapid Wave Kit', 'rapid-wave-kit-6a', 'Rapid Wave Kit is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/rapid-wave-kit-6a.png', 1, 'available', 0),
('Storm Orbit Device', 'storm-orbit-device-8', 'Storm Orbit Device is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/storm-orbit-device-8.png', 1, 'available', 0),
('Coastal Track Pack', 'coastal-track-pack-9', 'Coastal Track Pack is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/coastal-track-pack-9.png', 1, 'available', 0),
('Noble Field Pack', 'noble-field-pack-10', 'Noble Field Pack is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/noble-field-pack-10.png', 1, 'available', 0),
('Nova Flame Device', 'nova-flame-device-11', 'Nova Flame Device is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/nova-flame-device-11.png', 1, 'available', 0),
('Solar Arc Tool', 'solar-arc-tool-12', 'Solar Arc Tool is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/solar-arc-tool-12.png', 1, 'available', 0),
('Shadow Trail Pack', 'shadow-trail-pack-13', 'Shadow Trail Pack is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/shadow-trail-pack-13.png', 1, 'available', 0),
('Wild Harbor Kit', 'wild-harbor-kit-14', 'Wild Harbor Kit is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/wild-harbor-kit-14.png', 1, 'coming_soon', 0),
('Iron Echo Tool', 'iron-echo-tool-15', 'Iron Echo Tool is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/iron-echo-tool-15.png', 1, 'available', 1),
('Prism Blaze Device', 'prism-blaze-device-16', 'Prism Blaze Device is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/prism-blaze-device-16.png', 1, 'available', 0),
('Crimson Path Pack', 'crimson-path-pack-17', 'Crimson Path Pack is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/crimson-path-pack-17.png', 1, 'available', 1),
('Arctic Pulse Tool', 'arctic-pulse-tool-18', 'Arctic Pulse Tool is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/arctic-pulse-tool-18.png', 1, 'available', 0),
('Volcanic Ridge Tool', 'volcanic-ridge-tool-29', 'Volcanic Ridge Tool is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/volcanic-ridge-tool-29.png', 1, 'available', 0),
('Comet Trace Tool', 'comet-trace-tool-21', 'Comet Trace Tool is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/comet-trace-tool-21.png', 1, 'coming_soon', 0),
('Onyx Surge Pack', 'onyx-surge-pack-22', 'Onyx Surge Pack is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/onyx-surge-pack-22.png', 1, 'available', 0),
('Quantum Ash Device', 'quantum-ash-device-28', 'Quantum Ash Device is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/quantum-ash-device-28.png', 1, 'available', 0),
('Sunbeam Range Kit', 'sunbeam-range-kit-27', 'Sunbeam Range Kit is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/sunbeam-range-kit-27.png', 1, 'available', 0),
('Signal Glade Tool', 'signal-glade-tool-25', 'Signal Glade Tool is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/signal-glade-tool-25.png', 1, 'available', 0),
('Zenith Rock Kit', 'zenith-rock-kit-19', 'Zenith Rock Kit is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/zenith-rock-kit-19.png', 1, 'coming_soon', 1),
('Ember Crest Pack', 'ember-crest-pack-26', 'Ember Crest Pack is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/ember-crest-pack-26.png', 1, 'available', 1),
('Frost Hollow Device', 'frost-hollow-device-24', 'Frost Hollow Device is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/frost-hollow-device-24.png', 1, 'available', 0),
('Bright Echo Kit', 'bright-echo-kit-23', 'Bright Echo Kit is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/bright-echo-kit-23.png', 1, 'available', 0),
('Stealth Brook Device', 'stealth-brook-device-20', 'Stealth Brook Device is engineered for high-impact performance and built to thrive in extreme conditions. Its modular design ensures adaptability wherever adventure takes you.', 'products/stealth-brook-device-20.png', 1, 'available', 0);

INSERT INTO product_categories (product_id, category_id) VALUES
  (1, 2),
  (1, 6),
  (1, 7),
  (1, 8),
  (2, 4),
  (2, 7),
  (3, 1),
  (3, 2),
  (3, 5),
  (3, 6),
  (3, 8),
  (4, 2),
  (4, 5),
  (4, 6),
  (4, 7),
  (5, 5),
  (5, 6),
  (6, 5),
  (6, 6),
  (6, 8),
  (7, 1),
  (7, 4),
  (7, 6),
  (7, 8),
  (8, 2),
  (8, 7),
  (9, 5),
  (9, 6),
  (10, 2),
  (10, 4),
  (11, 2),
  (11, 5),
  (11, 6),
  (11, 8),
  (12, 2),
  (12, 4),
  (12, 7),
  (12, 8),
  (13, 1),
  (13, 5),
  (13, 7),
  (13, 8),
  (14, 4),
  (14, 5),
  (14, 6),
  (15, 2),
  (15, 5),
  (15, 6),
  (16, 2),
  (16, 4),
  (16, 6),
  (16, 7),
  (17, 4),
  (17, 6),
  (17, 8),
  (18, 2),
  (18, 4),
  (18, 5),
  (19, 2),
  (19, 4),
  (19, 5),
  (19, 8),
  (20, 5),
  (20, 6),
  (20, 7),
  (21, 2),
  (21, 4),
  (21, 5),
  (21, 8),
  (22, 2),
  (22, 6),
  (22, 8),
  (23, 1),
  (23, 2),
  (23, 6),
  (23, 7),
  (24, 4),
  (24, 6),
  (24, 8),
  (25, 2),
  (25, 4),
  (25, 5),
  (25, 7),
  (26, 1),
  (26, 2),
  (26, 4),
  (26, 6),
  (26, 7),
  (27, 4),
  (27, 6),
  (28, 4),
  (28, 5),
  (29, 1),
  (29, 2),
  (29, 7),
  (30, 8);

INSERT INTO product_prices (product_id, price, currency) VALUES
  (1, 12226, 'USD'),
  (2, 29970, 'USD'),
  (3, 13491, 'USD'),
  (4, 22636, 'USD'),
  (5, 22216, 'USD'),
  (6, 8116, 'USD'),
  (7, 24605, 'USD'),
  (8, 14632, 'USD'),
  (9, 16706, 'USD'),
  (10, 24574, 'USD'),
  (11, 8290, 'USD'),
  (12, 10684, 'USD'),
  (13, 25551, 'USD'),
  (14, 21687, 'USD'),
  (15, 23394, 'USD'),
  (16, 17669, 'USD'),
  (17, 6729, 'USD'),
  (18, 28143, 'USD'),
  (19, 5426, 'USD'),
  (20, 22526, 'USD'),
  (21, 15020, 'USD'),
  (22, 15284, 'USD'),
  (23, 20228, 'USD'),
  (24, 5805, 'USD'),
  (25, 26437, 'USD'),
  (26, 19396, 'USD'),
  (27, 28694, 'USD'),
  (28, 25561, 'USD'),
  (29, 11798, 'USD'),
  (30, 11497, 'USD');

INSERT INTO product_sale_prices (product_id, sale_price, currency) VALUES
  (1, 9169, 'USD'),
  (3, 10118, 'USD'),
  (4, 16977, 'USD'),
  (8, 10974, 'USD'),
  (10, 18430, 'USD'),
  (11, 6217, 'USD'),
  (12, 8013, 'USD'),
  (15, 17545, 'USD'),
  (16, 13251, 'USD'),
  (18, 21107, 'USD'),
  (19, 4069, 'USD'),
  (21, 11265, 'USD'),
  (22, 11463, 'USD'),
  (23, 15171, 'USD'),
  (25, 19827, 'USD'),
  (26, 14547, 'USD'),
  (29, 8848, 'USD');

INSERT INTO product_inventory (product_id, quantity_in_stock) VALUES
  (1, 42),
  (2, 47),
  (3, 20),
  (4, 2),
  (5, 23),
  (6, 32),
  (7, 8),
  (8, 34),
  (9, 31),
  (10, 31),
  (11, 7),
  (12, 13),
  (13, 40),
  (14, 50),
  (15, 5),
  (16, 49),
  (17, 45),
  (18, 50),
  (19, 13),
  (20, 30),
  (21, 28),
  (22, 6),
  (23, 32),
  (24, 19),
  (25, 38),
  (26, 16),
  (27, 47),
  (28, 27),
  (29, 4),
  (30, 23);