name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: '.lighthouserc.json'
          urls: |
            https://mercora.russellkmoore.workers.dev
            https://mercora.russellkmoore.workers.dev/category/featured
            https://mercora.russellkmoore.workers.dev/checkout
          uploadArtifacts: true
          temporaryPublicStorage: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR with Lighthouse results
        uses: treosh/lighthouse-ci-action@v11
        if: github.event_name == 'pull_request'
        with:
          configPath: '.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}